sudo: required

language: java

services:
  - docker

install:
  - docker build . -t test

script:
  - docker run -v `pwd`/$TRAVIS_BUILD_DIR:/$TRAVIS_BUILD_DIR -w="/$TRAVIS_BUILD_DIR" test gauge run specs
