sudo: required

language: java

services:
  - docker

install:
  - docker build . -t test
  # use Docker_zip if you want to install using a zip installer

script:
  - docker run -v `pwd`:/dest -w="/dest" test gauge run specs
