sudo: required

language: java

services:
  - docker

install:
  - docker build . -t gaugeDocker

script:
  - docker run -v `pwd`/$TRAVIS_BUILD_DIR:/$TRAVIS_BUILD_DIR -w="/$TRAVIS_BUILD_DIR" gaugeDocker gauge run specs
