FROM ubuntu

# Install Java.
RUN apt-get update
RUN apt-get -q -y install default-jdk

RUN apt-get update && \
      apt-get -y install wget && \
      apt-get -y install unzip && \
      apt-get -y install sudo && \
      apt-get -y install curl && \
      apt-get install apt-transport-https -y

ADD ./install_latest.sh install_latest.sh
RUN chmod +x ./install_latest.sh
RUN ./install_latest.sh
RUN gauge install java
